#!/usr/bin/env python3
"""Set up the Vue3 frontend for e2e testing against the local Rust backend.

Creates `.env.development.local` in the Vue project to override the Vite proxy
target, pointing `/api` at the local Rust backend instead of the remote dev
server. Skips pnpm install in WSL (cross-platform node_modules incompatibility).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import RUST_PORT, VUE_FRONTEND  # noqa: E402
from log import info, warn, error  # noqa: E402

TARGET = "e2e::setup"


def _is_wsl() -> bool:
    """Detect if running inside WSL."""
    try:
        with open("/proc/version", encoding="utf-8", errors="replace") as f:
            return "microsoft" in f.read().lower()
    except Exception:
        return False


def ensure_env_override() -> None:
    """Create .env.development.local to proxy /api → local Rust backend."""
    env_local = VUE_FRONTEND / ".env.development.local"
    content = f"""\
# Auto-generated by e2e/setup_frontend.py — do not commit.
# Points the Vite dev proxy at the local Rust backend.
VITE_API_BASE=/api
VITE_API_PROXY_TARGET=http://127.0.0.1:{RUST_PORT}
VITE_WS_BASE=ws://127.0.0.1:{RUST_PORT}/ws
"""
    env_local.write_text(content, encoding="utf-8")
    info(TARGET, f"Wrote {env_local}")

    # Ensure .gitignore has the entry
    gitignore = VUE_FRONTEND / ".gitignore"
    if gitignore.exists():
        lines = gitignore.read_text(encoding="utf-8").splitlines()
        if ".env.*.local" not in lines and ".env.development.local" not in lines:
            with open(gitignore, "a", encoding="utf-8") as fh:
                fh.write("\n# e2e local override\n.env.*.local\n")
            info(TARGET, f"Added .env.*.local to {gitignore}")


def ensure_deps() -> bool:
    """Ensure node_modules exists. Returns True if ready, False if not.

    In WSL, pnpm install on a Windows-mounted path (/mnt/d/...) fails because
    pnpm tries to use Windows pnpm and node_modules are platform-specific.
    We skip install in WSL and just check if node_modules already exists.
    """
    node_modules = VUE_FRONTEND / "node_modules"
    if node_modules.exists() and any(node_modules.iterdir()):
        count = sum(1 for _ in node_modules.iterdir())
        if count > 10:
            info(TARGET, f"node_modules has {count} entries — ready")
            return True

    if _is_wsl():
        warn(TARGET, "Running in WSL — cannot run pnpm install on /mnt/ path.")
        warn(TARGET, f"Please install deps on Windows: cd {VUE_FRONTEND} && pnpm install")
        return node_modules.exists()

    info(TARGET, "Running pnpm install...")
    result = subprocess.run(
        ["pnpm", "install"],
        cwd=str(VUE_FRONTEND),
        shell=True,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        error(TARGET, f"pnpm install failed:\n{result.stderr}")
        return False
    info(TARGET, "pnpm install complete")
    return True


def main() -> int:
    if not VUE_FRONTEND.exists():
        error(TARGET, f"Vue frontend not found at {VUE_FRONTEND}")
        return 1

    ensure_env_override()
    ready = ensure_deps()
    if ready:
        info(TARGET, "Frontend ready for e2e testing.")
    else:
        warn(TARGET, "Frontend deps not ready, but continuing anyway.")
    return 0  # Always return 0 — don't block the dev stack


if __name__ == "__main__":
    raise SystemExit(main())
